[package]
name = "rucron"
version = "0.1.2"
edition = "2021"
authors = ["Ban Mengtao <jiuxie@outlook.com>"]
keywords = ["rust", "cron", "crontab", "scheduler"]
description = "A Rust Job Scheduling Crate."
license = "MIT"
repository = "https://github.com/goldwind-ting/rucron/"

[dependencies]
tokio = { version = "1.14.0", features = ["time", "full"] }
futures = "0.3.17"
lazy_static = "1.4.0"
signal-hook = "0.3.12"
chrono = "0.4.19"
http = "0.2.5"
async-trait = "0.1.52"
log = "0.4.14"
dashmap = "5.0.0"
thiserror = "1.0.30"
serde_json = "1.0.74"
serde = { version = "1.0.133", features = ["derive"] }

[dev-dependencies]
redis = "0.21.4"
rand = "0.8.4"

[[example]]
name = "redlocker"
path = "examples/redlocker.rs"
