[package]
name = "rucron"
version = "0.1.1"
edition = "2021"
authors = ["Ban Mengtao <jiuxie@outlook.com>"]
keywords = ["rust", "cron", "crontab", "scheduler"]
description = "A Rust Job Scheduling Crate."
license = "MIT"
repository = "https://github.com/goldwind-ting/rucron/"

[dependencies]
tokio = { version = "1.14.0", features = ["time", "full"] }
futures = "0.3.17"
lazy_static = "1.4.0"
signal-hook = "0.3.12"
chrono = "0.4.19"

[dev-dependencies]
redis = "0.21.4"

[[example]]
name = "redlocker"
path = "examples/redlocker.rs"
